### ISSUE TITLE
html layout problem

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio-embed-app#1]
<img width="1426" alt="screen shot 2016-04-29 at 11 13 22 am" src="https://cloud.githubusercontent.com/assets/288005/14925314/bae70e22-0dfb-11e6-8d36-44bab26a2f8b.png">

**Comment by esjewett** [comment]
This is probably caused by out of sync versions. I've updated the bower.json so that using `bower link` should no longer be necessary. If you pull down the latest master branch and `bower install`, I hope it fixes the issue.

**Comment by cncoleman** [comment]
Now it looks like this:
<img width="680" alt="screen shot 2016-04-29 at 2 11 00 pm" src="https://cloud.githubusercontent.com/assets/288005/14929810/5144821a-0e14-11e6-9142-f56fbd84fd61.png">

**Comment by esjewett** [comment]
Still broken. What does the error console look like? And the result of running "bower install" in the directory?

On Fri, Apr 29, 2016 at 2:11 PM -0700, "Nicole Coleman" notifications@github.com wrote:

Now it looks like this:

**Comment by cncoleman** [comment]
Ah! Thank you. The problem was in the bower install. It saw and existing non-bower directory with that name in the components directory (bower_components/palladio). I forced the installation with --force.
