### ISSUE TITLE
Where is the facet filter component?

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio-embed-app#2]
It's not an option when I load the Voltaire _map save file. Do I need to configure it in Palladio first?

**Comment by cncoleman** [comment]
Yes. It needs to be configured in Palladio app first.

**Comment by esjewett** [comment]
Yeah, this is actually a problem with the views rather than the filters. Right now the embed app displays the option to insert views even if they are not in the save file, which is a bit wrong.
