### ISSUE TITLE
Remove "Review" checkbox and character pills from Metavis component

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio-embed-app#6]
I don't remember where the "review" came from, but it is not helpful. Would be best to lose it. 

![screen shot 2016-10-20 at 4 28 43 pm](https://cloud.githubusercontent.com/assets/288005/19581546/7807ac0e-96e2-11e6-908d-9466c9bddb69.png)

**Comment by esjewett** [comment]
Moving this over to the metavis component repo.
