### ISSUE TITLE
Timeline tooltip 

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio-embed-app#8]
when you choose not to have a group in a timeline, the tooltip still appears with the value "no group". If no group is assigned, there should be no tooltip. 
![screen shot 2016-10-25 at 9 39 44 am](https://cloud.githubusercontent.com/assets/288005/19695233/3c9ace86-9a97-11e6-85d0-861bfb7957cf.png)

**Comment by esjewett** [comment]
I think this was a stop-gap measure to make it a little easier to manage the case where no group is selected. I would agree that the tooltip should not display at all and will look into that under the issue in the timeline component referenced above.

**Comment by esjewett** [comment]
This should be resolved in palladio-timeline-component version 1.0.6. Can you switch to this in the RoL app?
